#!/bin/bash

set -e
DIR="$(dirname $0)"

echo "Decrypting $1"
openssl smime -decrypt -binary -in "$DIR/tmp/$1" -inform DER -out "$DIR/tmp/$1.tar" -inkey private.pem

tar -C "$DIR/tmp" -xf "$DIR/tmp/$1.tar"
mv "$DIR/tmp/value.seal" "$DIR/uploads/$1-V.seal"
mv "$DIR/tmp/filter.seal" "$DIR/uploads/$1-F.seal"

rm "$DIR/tmp/$1"
rm "$DIR/tmp/$1.tar"

echo "SUCCESS"
